name: '[Auto] .github Sync'

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  reuse:
    uses: sator-imaging/.github/.github/workflows/Auto-dot-github-Sync.yml@main
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
